inventory:
  hosts: hosts.yaml
  configs: configs.yaml

variables:
  "£hosts": 
    - pando
    # - calmip
  "£atari":   "--job=$SLURM_JOB_ID --net=conv --episode_frames=27000 --stack_frames=4 --max_frames=1000000000 --max_evals=10000000"
  "£minatar": "--job=$SLURM_JOB_ID --net=min --episode_frames=27000 --max_frames=100000000 --max_evals=10000000"
  "£mujoco":  "--job=$SLURM_JOB_ID --episode_frames=1000 --max_frames=100000000 --max_evals=10000000"
  "£procgen": "--net=impala --episode_frames=1000 --stack_frames=1 --max_frames=250000000 --max_evals=10000000 --job=$SLURM_JOB_ID"

tasks:
  - name: "Run Procgen"
    hosts:
      # - calmip
      - pando
    slurm:
      job_name: "Procgen"
      cmd: "mprof run python3 Rayvolution/simple.py £procgen --pop=96 --mu=48"
      config: procgen_light
      ray: true
      scatter: false
      seeds: 0
      sweep:
        "--optim": 
          - canonical
          # - sepcma
        "--seeding": 
          - random
          # - unique
          # - generation
        "--sampling":
          - mc
          # - dynamic
          # - default
          # - static
          # - smc
        "--es_seed": [1]
        "--eval_budget": [5]
        "--batch_rs": [5]
        "--mc_samples": [25]
        "--noise_type": 
          - none
        "--wandb": ["sureli/rayvolution"]
        "--tag": ["procgen-calmip"]
      args:
        - "--env=bigfish-easy"
        # - "--env=starpilot-easy"
        # - "--env=bossfight-easy"
        # - "--env=bigfish-hard"
        # - "--env=leaper-easy"