inventory:
  hosts: hosts.yaml
  configs: configs.yaml

variables:
  "£hosts": 
    - pando
    # - calmip
  "£atari":   "--job=$SLURM_JOB_ID --net=conv --episode_frames=27000 --stack_frames=4 --max_frames=1000000000 --max_evals=10000000"
  "£minatar": "--job=$SLURM_JOB_ID --net=min --episode_frames=27000 --max_frames=10000000 --max_evals=10000000"
  "£mujoco":  "--job=$SLURM_JOB_ID --episode_frames=1000 --max_frames=100000000 --max_evals=10000000"
  "£procgen": "--net=impala --episode_frames=1000 --stack_frames=1 --max_frames=250000000 --max_evals=10000000 --job=$SLURM_JOB_ID"
  "£control":
    - "--env=MountainCar-v0 --max_frames=10000000"
    - "--env=CartPole-v1 --max_frames=500000"
    - "--env=LunarLander-v2 --max_frames=1000000"
    - "--env=Acrobot-v1 --max_frames=10000000"

tasks:
  - name: "Gym standalone"
    hosts:
      - pando
    slurm:
      job_name: "Gym"
      cmd: "python3 Rayvolution/simple_rl.py --save_freq=10 --noise_type=none --job=$SLURM_JOB_ID"
      config: gpu
      ray: false
      scatter: true
      seeds: 0
      sweep:
        "--rl": ["munchausen"]
        "--replay_start_size": [4096]
        "--rl_batch_size": [4096]
        "--rl_lr": [0.001]
        "--epsilon_min": [0.2]
        "--buffer_size": [2000000]
        "--seeding": ["random"]
        "--wandb": ["sureli/rayvolution"]
        "--tag": ["linear_epsilon"]
      args: 
        - "--env=LunarLander-v2 --max_frames=1000000"
        - "--env=CartPole-v1 --max_frames=500000"
        - "--env=MountainCar-v0 --max_frames=10000000"
        - "--env=Acrobot-v1 --max_frames=10000000"


  # - name: "Minatar standalone"
  #   hosts:
  #     - pando
  #   slurm:
  #     job_name: "Minatar"
  #     cmd: "python3 Rayvolution/simple_rl.py £minatar --save_freq=10 --noise_type=none --job=$SLURM_JOB_ID"
  #     config: gpu
  #     ray: false
  #     scatter: true
  #     seeds: 0
  #     sweep:
  #       "--rl": ["munchausen"]
  #       "--replay_start_size": [4096]
  #       "--rl_lr": [0.001]
  #       "--epsilon_min": [0.2]
  #       "--epsilon_decay": [0.999]
  #       "--rl_batch_size": [4096]
  #       "--buffer_size": [1000000]
  #       "--seeding": ["random"]
  #       "--wandb": ["sureli/rayvolution"]
  #       "--tag": ["param_search"]
  #     args:
  #       # - "--env=min-breakout"
  #       - "--env=min-seaquest"
  #       - "--env=min-asterix"
  #       - "--env=min-freeway"
  #       - "--env=min-space_invaders"
