inventory:
  hosts: hosts.yaml
  configs: configs.yaml

variables:
  "£hosts": 
    - pando
    # - calmip
  "£atari":   "--job=$SLURM_JOB_ID --net=conv --episode_frames=27000 --stack_frames=4 --max_frames=1000000000 --max_evals=10000000"
  "£minatar": "--job=$SLURM_JOB_ID --net=min --episode_frames=27000 --max_frames=100000000 --max_evals=10000000"
  "£mujoco":  "--job=$SLURM_JOB_ID --episode_frames=1000 --max_frames=100000000 --max_evals=10000000"
  "£procgen": "--net=impala --episode_frames=1000 --stack_frames=1 --max_frames=250000000 --max_evals=10000000 --job=$SLURM_JOB_ID"
  "£tasks":
    - "--net=mujoco-light --env=HalfCheetah-v2"
    # - "--net=mujoco-light --env=InvertedDoublePendulum-v2"  
    - "--net=mujoco-light --env=Swimmer-v2"
    # - "--net=mujoco-light --env=Hopper-v2"
    - "--net=mujoco-light --env=InvertedPendulum-v2"
    # - "--net=mujoco-light --env=Walker2d-v2"


tasks:
  - name: "Test TD3 baseline"
    hosts:
      - pando
    slurm:
      job_name: "TD3_Baseline"
      cmd: "python3 Rayvolution/simple.py £mujoco --pop=24 --mu=12  --max_evals=10000000 --save_freq=10 --sigma=0.1 --noise_type=none --seeding=random --buffer_size=1000000 --job=$SLURM_JOB_ID"
      config: medium
      ray: true
      scatter: true
      seeds: 0
      sweep:
        "--rl": ["td3"]
        "--rl_steps": [1000, 3000]
        "--backprop_es": [0]
        "--actor_injection": [0]
        "--es_seed": [0, 1]
        "--optim": ["sepcma"]
        "--wandb": ["sureli/rayvolution"]
        "--tag": ["baseline"]
      args: £tasks


  - name: "Test TD3 injection"
    hosts:
      - pando
    slurm:
      job_name: "TD3_Injection"
      cmd: "python3 Rayvolution/simple.py £mujoco --pop=24 --mu=12  --max_evals=10000000 --save_freq=10 --sigma=0.1 --noise_type=none --seeding=random --buffer_size=1000000 --job=$SLURM_JOB_ID"
      config: medium
      ray: true
      scatter: true
      seeds: 0
      sweep:
        "--rl": ["td3"]
        "--rl_steps": [1000]
        "--rl_lr": [0.0001, 0.001]
        "--rl_batch_size": [4096, 256, 1024]
        "--backprop_es": [0]
        "--actor_injection": [1]
        "--es_seed": [0, 1]
        "--optim": ["sepcma"]
        "--wandb": ["sureli/rayvolution"]
        "--tag": ["injection"]
      args: £tasks