default:
  cpus:
    pando: 24
    calmip: 36
    localhost: 8
    ninox: 16
  gpu: False
  time: 0-12:00:00
  mail: True
  mail-user: paul.templier@isae-supaero.fr

sentinel:
  cpus: 1
  time: 1-00:00:00

single:
  cpus: 1
  time: 01:00:00

test:
  cpus: 1
  time: 00:05:00
  partition:
    pando: debug

light:
  cpus:
    pando: 48
    calmip: 72
    localhost: 8
    ninox: 16
  time: 1-00:00:00

medium:
  cpus:
    pando: 48
    calmip: 72
    localhost: 8
    ninox: 16
  time: 1-00:00:00

heavy:
  cpus:
    pando: 384
    calmip: 396
    localhost: 8
    ninox: 16
  partition:
    pando: medium
  time: 1-00:00:00

long:
  cpus:
    pando: 24
    calmip: 36
    localhost: 8
    ninox: 16
  partition:
    pando: long
  time: 7-00:00:00

debug:
  cpus:
    pando: 48
    calmip: 72
    localhost: 8
    ninox: 16
  partition:
    pando: debug
  time: 01:00:00

# SPECIFIC CONFIGS

mujoco:
  cpus:
    pando: 48
    calmip: 72
    localhost: 8
    ninox: 16
  partition:
    pando: short
  time: 1-00:00:00

raytest:
  cpus:
    pando: 72
    calmip: 72
    localhost: 8
    ninox: 16
  partition:
    pando: short
  time: 00:10:00


atari:
  cpus:
    pando: 384
    calmip: 396
    localhost: 8
    ninox: 16
  partition:
    pando: medium
  time: 1-00:00:00

atari_half:
  cpus:
    pando: 192
    calmip: 216
    localhost: 8
    ninox: 16
  partition:
    pando: medium
  time: 06:00:00

atari_full:
  cpus:
    pando: 768
    calmip: 828
    localhost: 8
    ninox: 16
  partition:
    pando: medium
  time: 06:00:00

procgen:
  cpus:
    pando: 192
    calmip: 180
    localhost: 8
    ninox: 16
  partition:
    pando: medium
  time: 1-00:00:00

procgen_light:
  cpus:
    pando: 96
    calmip: 216
    localhost: 8
    ninox: 16
  partition:
    pando: short
  time: 1-00:00:00

sepcma:
  cpus:
    pando: 48
    calmip: 36
    localhost: 8
    ninox: 16
  partition:
    pando: short
  time: 1-00:00:00

