pando:
  user: p.templier
  host: pando.isae.fr
  cpus_per_node: 24
  platform: slurm
  wandb: online
  gpu: True
  save_path: "/scratch/disc/p.templier/slurm_logs"
  init: |
    module purge
    module load python/3.7
    module load libosmesa/17.2.3
    module load cuda/11.6
    cd /home/disc/p.templier/parallelpy
    source pyenv/bin/activate
    echo $(which python)
    cd

pando_ssh:
  user: p.templier
  host: "pando.isae.fr"
  cpus_per_node: 24
  platform: slurm
  wandb: online
  gpu: True
  save_path: "/scratch/disc/p.templier/slurm_logs"
  init: |
    module purge
    module load python/3.7
    module load libosmesa/17.2.3
    cd /home/disc/p.templier/parallelpy
    source pyenv/bin/activate
    echo $(which python)
    cd

# export OMP_NUM_THREADS=1
# module purge
# module load python/3.7
# module load gcc/8.2.0 
# module load openmpi/4.0.0-gcc8.2
# module load mpi4py/3.0.1-openmpi4.0.0-gcc8.2-python3.7
# module load libosmesa/17.2.3
# cd /home/disc/p.templier/parallelpy
# source pyenv/bin/activate
# echo $(which python)
# cd

calmip:
  user: templier
  host: olympe.calmip.univ-toulouse.fr
  cpus_per_node: 36
  platform: slurm
  wandb: offline
  gpu: True
  save_path: "/tmpdir/templier/slurm_logs"
  init: |
    export OMP_NUM_THREADS=1
    module purge
    module load intel/18.2
    module load misc-libs/libOSMesa
    module load intelmpi/18.2
    module load python/3.6.8
    source activate /tmpdir/templier/envs/torchenv
    cd

calmip2:
  user: p21049tp
  host: olympe.calmip.univ-toulouse.fr
  cpus_per_node: 36
  platform: slurm
  wandb: offline
  gpu: True
  save_path: "/tmpdir/p21049tp/slurm_logs"
  init: |
    export OMP_NUM_THREADS=1
    module purge
    module load intel/18.2
    module load misc-libs/libOSMesa
    module load intelmpi/18.2
    module load python/3.6.8
    source activate /tmpdir/p21049tp/envs/myenv
    cd

localhost:
  user: p.templier
  host: localhost
  cpus_per_node: 8
  platform: linux
  gpu: False

ninox:
  user: sureli
  host: 10.70.3.216
  cpus_per_node: 16
  platform: linux
  gpu: True

raspi:
  user: pi
  host: groinkbot.hopto.org
  cpus_per_node: 4
  platform: linux
  gpu: False

sureli1:
  user: sureli
  host: 10.70.3.216
  cpus_per_node: 20
  platform: linux
  gpu: True

sureli2:
  user: sureli
  host: 10.70.3.216
  cpus_per_node: 20
  platform: linux
  gpu: True