inventory:
  hosts: hosts.yaml
  configs: configs.yaml

tasks:
  # - name: "Git push BERL"
  #   hosts:
  #     - localhost
  #   git:
  #     action: push
  #     path: "/home/disc/p.templier/Documents/Doctorat/Dev/BERL"

  - name: "Git pull BERL"
    hosts:
      - calmip
    git:
      path: "~/BERL"

  - name: "Run Atari"
    hosts:
      - calmip
    srun:
      job_name: "BERL"
      cmd: "srun python BERL/run.py --wandb=sureli/BERL_paper --seed=$seed --job=$SLURM_JOB_ID --save_freq=50 --preset calmip atari openai --pop_per_cpu=2"
      config: atari
      seeds: 0 1
      sweep:
        "--tag": ["weight_decay"]
        "--es_wd": [0.001]
        "--es_sigma": [0.02]
        "--es_lr": [0.01]
        "--es_momentum": [0.9]
      args:
        - "--net=canonical --env=Pong-v0"
