inventory:
  hosts: hosts.yaml
  configs: configs.yaml

variables:
  "£hosts": 
    - pando
    # - calmip
  "£atari": "--net=conv --episode_frames=27000 --stack_frames=4"
  "£minatar": "--net=min --mu=12 --episode_frames=27000"
  "£mujoco": "--mu=12 --episode_frames=1000"
  "£procgen": "--net=impala --episode_frames=1000 --stack_frames=1"

tasks:
  - name: "Git pull"
    hosts:
      - pando
      - calmip
    git:
      action: pull
      path: "~/Rayvolution"

  # - name: "Run Atari"
  #   hosts:
  #     # - calmip
  #     - pando
  #   slurm:
  #     job_name: "Atari"
  #     cmd: "python3 Rayvolution/simple.py £atari --pop=24 --mu=12 --max_frames=1000000000 --max_evals=10000000"
  #     config: sepcma
  #     ray: true
  #     scatter: true
  #     seeds: 0
  #     sweep:
  #       "--optim": ["canonical", "sepcma"]
  #     args:
  #       - "--env=Pong-v0"
  #       - "--env=Alien-v0"

  - name: "Run Procgen"
    hosts:
      - calmip
      # - pando
    slurm:
      job_name: "Procgen"
      cmd: "python3 Rayvolution/simple.py £procgen --pop=24 --mu=12 --max_frames=1000000000 --max_evals=10000000"
      config: sepcma
      ray: true
      scatter: true
      seeds: 0
      sweep:
        # "--optim": ["sepcma", "canonical"]
        # "--seeding": ["random", "unique", "generation"]
        "--wandb": ["sureli/rayvolution"]
      args:
        - "--env=bigfish-easy"
        # - "--env=leaper-easy"
        # - "--env=bossfight-easy"
        # - "--env=starpilot-easy"
